config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root
  root 'static_pages#home'

  # staticPages
  get '/home',  to: 'static_pages#home',  as: 'static_pages_home'
  get '/about', to: 'static_pages#about', as: 'static_pages_about'

  # users
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  # get '/users/:id', to: 'users#show'
  resources :users, only: [:show]

  # sessions
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,
    presence: true,
    length: {maximum: 99}

  validates :email,
    presence: true,
    length: {maximum: 255},
    uniqueness: {case_sensitive: false},
    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}

  validates :password,
    presence: true,
    length: {minimum: 5}

  has_secure_password

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ?
        BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost

      BCrypt::Password.create(string, cost: cost)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = '入力した内容が正しくありません。ご確認のうえ再度お試しください。'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      log_in @user
      redirect_to @user, flash: {success: 'Welcome Test!'}
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title='')
    static_title = ' | Hello'
    title.empty? ? static_title : "#{title}#{static_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザを返す。
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # ユーザがログインしていれば、true
  # その他なら false
  def logged_in?
    !current_user.nil?
  end

  # ログアウト
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title=page_title(yield(:title))
    =csrf_meta_tags
    =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header#header.navbar.navbar-fixed-top.navbar-inverse
      .container
        %p#logo=link_to page_title.gsub('|', '').strip!, root_path
        =render '/shared/header'

    %main.container
      #flash.container
        -flash.each do |msg_type, msg|
          %p.alert{class: "alert-#{msg_type}"}=msg

      %h1=yield(:title)
      = yield

    %footer#footer.clearfix
      .container
        =render '/shared/footer'

    =debug(params) if Rails.env.development?

app/views/shared/_errors.html.haml
-if o.kind_of?(ApplicationRecord)
  -if o.errors.any?
    .alert.alert-danger
      %ul
        -o.errors.full_messages.each do |err|
          %li=err

app/views/shared/_footer.html.haml
%nav
  %ul.nav.navbar-nav.navbar-right
    %li=link_to 'Home', static_pages_home_path
    %li=link_to 'About', static_pages_about_path

app/views/shared/_header.html.haml
%nav
  %ul.nav.navbar-nav.navbar-right
    -#%li=link_to 'Home', static_pages_home_path
    -if logged_in?
      %li=link_to 'Users', '#'
      %li.dropdown
        %a.dropdown-toggle{href: '#', 'data-toggle': 'dropdown'}
          Account: 
          %span.caret
        %ul.dropdown-menu
          %li=link_to 'プロフィール', current_user
          %li=link_to '環境設定', '#'
          %li.divider
          %li=link_to 'Logout', logout_path, method: :delete
    -else
      %li=link_to 'Login', login_path

app/views/static_pages/about.html.haml
:ruby
  provide(:title, 'StaticPages#about')

app/views/static_pages/home.html.haml
:ruby
  provide(:title, 'StaticPages#home')

%p.text-center=link_to 'Sign up', signup_path, class: 'btn btn-primary center'

app/views/users/_form.html.haml
=form_for(@user, url: signup_path) do |f|
  =render '/shared/errors', {o: @user}
  %p
    =f.label :name, 'お名前'
    =f.text_field :name, class: 'form-control'
  %p
    =f.label :email, 'メールアドレス'
    =f.email_field :email, class: 'form-control'
  %p
    =f.label :password, 'パスワード'
    =f.password_field :password, class: 'form-control'
  %p
    =f.label :password_confrimation, 'パスワード(確認)'
    =f.password_field :password_confrimation, class: 'form-control'
  %p=f.submit 'Create account', class: 'btn btn-primary'

app/views/users/new.html.haml
:ruby
  provide(:title, 'Sign up')

=render '/users/form'

app/views/users/show.html.haml
:ruby
  provide(:title, 'Show')